services:
  backend:
    build: ./backend
    env_file:
      - path: ./backend/.env
        required: false
    environment:
      ENVIRONMENT: local
    ports:
      - "8000:8000"

  frontend:
    build: ./frontend
    environment:
      BACKEND_HOST: backend
      BACKEND_PORT: 8000
    ports:
      - "3000:8080"
    depends_on:
      - backend
